version: '3.8'

services:
  web:
    image: php:apache
    container_name: servidor-php
    ports:
      - "8080:80"
    volumes:
      - ./miranda:/var/www/html
    restart: always
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    command: >
      bash -c "chown -R www-data:www-data /var/www/html &&
               chmod -R 755 /var/www/html &&
               apache2-foreground"
